ccflags-y += -I$(obj)/../include

obj-y += \
    init.o \
	def.o \
	dns.o \
	inet_chksum.o \
	ip.o \
	mem.o \
	memp.o \
	netif.o \
	pbuf.o \
	raw.o \
	stats.o \
	sys.o \
	altcp.o \
	altcp_alloc.o \
	altcp_tcp.o \
	tcp.o \
	tcp_in.o \
	tcp_out.o \
	timeouts.o \
	udp.o
	
obj-y += ipv4/